import 'package:image_picker/image_picker.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import '../models/junkshop.dart';

/// Repository that wraps all Supabase queries related to junkshops.
///
/// Constructor takes a [SupabaseClient] so it can be injected in tests or
/// provided via Riverpod.
class SupabaseShopRepository {
  const SupabaseShopRepository(this._client);

  final SupabaseClient _client;

  // ── Fetch ──────────────────────────────────────────────────────────────────

  /// Returns all shops with status `pending` or `verified`.
  ///
  /// The PostGIS `location` geography column is projected server-side as plain
  /// float columns `lat` and `lng` so [JunkshopModel.fromSupabaseRow] receives
  /// standard numeric values.
  Future<List<JunkshopModel>> fetchShops() async {
    final rows = await _client
        .from('junkshops')
        .select(
          '*, ST_Y(location::geometry) AS lat, ST_X(location::geometry) AS lng',
        )
        .inFilter('status', ['pending', 'verified']);

    return rows.map<JunkshopModel>(JunkshopModel.fromSupabaseRow).toList();
  }

  /// Fetches a single shop by [shopId]. Returns `null` if not found.
  Future<JunkshopModel?> fetchShop(String shopId) async {
    final rows = await _client
        .from('junkshops')
        .select(
          '*, ST_Y(location::geometry) AS lat, ST_X(location::geometry) AS lng',
        )
        .eq('id', shopId)
        .limit(1);

    if (rows.isEmpty) return null;
    return JunkshopModel.fromSupabaseRow(rows.first);
  }

  // ── Insert ─────────────────────────────────────────────────────────────────

  /// Inserts a new shop record and returns the DB-generated `id` and
  /// `edit_token`.
  ///
  /// [payload] must contain all required fields except `id` and `edit_token`,
  /// which are generated by the database.
  Future<({String id, String editToken})> insertShop(
    Map<String, dynamic> payload,
  ) async {
    final rows = await _client
        .from('junkshops')
        .insert(payload)
        .select('id, edit_token');

    final row = rows.first;
    return (id: row['id'] as String, editToken: row['edit_token'] as String);
  }

  // ── Rate limiting ──────────────────────────────────────────────────────────

  /// Returns `true` if the device has already submitted a shop within the last
  /// 24 hours (i.e. the rate limit has been hit).
  Future<bool> checkRateLimit(String deviceId) async {
    final cutoff = DateTime.now()
        .subtract(const Duration(hours: 24))
        .toIso8601String();

    final rows = await _client
        .from('junkshops')
        .select('id')
        .eq('device_id', deviceId)
        .gte('submitted_at', cutoff)
        .limit(1);

    return rows.isNotEmpty;
  }

  // ── Photo upload ───────────────────────────────────────────────────────────

  /// Uploads [file] to the `storefront-photos` Supabase Storage bucket at the
  /// path `<shopId>/storefront.jpg` and returns the public URL.
  Future<String> uploadPhoto(String shopId, XFile file) async {
    final bytes = await file.readAsBytes();
    final path = '$shopId/storefront.jpg';

    await _client.storage
        .from('storefront-photos')
        .uploadBinary(
          path,
          bytes,
          fileOptions: const FileOptions(
            contentType: 'image/jpeg',
            upsert: true,
          ),
        );

    return _client.storage.from('storefront-photos').getPublicUrl(path);
  }

  // ── Token-gated update ─────────────────────────────────────────────────────

  /// Calls the `update_shop_with_token` RPC to update editable shop fields.
  ///
  /// Returns `true` if the update succeeded, `false` if the token was invalid
  /// or the shop was not found.
  Future<bool> updateShopWithToken(
    String shopId,
    String editToken, {
    required String name,
    required String ownerName,
    required String contactNumber,
    required String schedule,
  }) async {
    final result = await _client.rpc(
      'update_shop_with_token',
      params: {
        'p_shop_id': shopId,
        'p_edit_token': editToken,
        'p_name': name,
        'p_owner_name': ownerName,
        'p_contact_number': contactNumber,
        'p_schedule': schedule,
      },
    );

    // The RPC returns a JSONB object: { "success": true } or { "error": "..." }
    if (result is Map<String, dynamic>) {
      return result['success'] == true;
    }
    return false;
  }

  // ── Token validation ───────────────────────────────────────────────────────

  /// Validates [editToken] for [shopId] by fetching the shop's current values
  /// and performing a no-op update via [updateShopWithToken].
  ///
  /// Returns `true` if the token is valid, `false` otherwise.
  Future<bool> validateToken(String shopId, String editToken) async {
    final shop = await fetchShop(shopId);
    if (shop == null) return false;

    return updateShopWithToken(
      shopId,
      editToken,
      name: shop.name,
      ownerName: shop.ownerName,
      contactNumber: shop.contactNumber,
      schedule: shop.schedule,
    );
  }
}
