-- Migration: 001_create_junkshops
-- Creates the junkshops table with PostGIS geography support,
-- all registration fields, relaxed contact_number CHECK (allows 'N/A'
-- for migrated legacy records), and three performance indexes.

-- Enable PostGIS extension (idempotent)
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE junkshops (
  -- Primary key
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Shop identity
  name                 TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
  owner_name           TEXT NOT NULL CHECK (char_length(owner_name) BETWEEN 1 AND 100),
  contact_number       TEXT NOT NULL
                         CHECK (
                           contact_number ~ '^\+?[0-9]{10,15}$'
                           OR contact_number = 'N/A'
                         ),
  address              TEXT NOT NULL DEFAULT '',
  municipality         TEXT NOT NULL DEFAULT '',

  -- Geographic location (WGS-84)
  location             GEOGRAPHY(POINT, 4326) NOT NULL,

  -- Shop details
  category             TEXT NOT NULL DEFAULT 'General Scrap',
  schedule             TEXT NOT NULL DEFAULT '',
  accepted_materials   TEXT[] NOT NULL DEFAULT '{}',

  -- Storefront photo (uploaded to Supabase Storage)
  storefront_photo_url TEXT,

  -- Lifecycle status
  status               TEXT NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending', 'verified', 'rejected')),

  -- Edit token for no-auth owner edits (UUID generated by DB)
  edit_token           UUID NOT NULL DEFAULT gen_random_uuid(),

  -- Device fingerprint for rate-limiting
  device_id            TEXT NOT NULL DEFAULT '',

  -- Timestamps
  submitted_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  verified_at          TIMESTAMPTZ,
  rejected_at          TIMESTAMPTZ,
  rejection_reason     TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index 1: PostGIS spatial index for proximity / bounding-box queries
CREATE INDEX junkshops_location_idx
  ON junkshops
  USING GIST (location);

-- Index 2: Composite index for device rate-limit window queries
--   (device_id = $1 AND submitted_at > now() - interval '24 hours')
CREATE INDEX junkshops_device_submitted_idx
  ON junkshops (device_id, submitted_at DESC);

-- Index 3: Index for status-filtered queries (pending/verified map load)
CREATE INDEX junkshops_status_idx
  ON junkshops (status);
